### ISSUE TITLE
alias?

### ISSUE THREAD

**Issue by Felix-44** [Felix-44/Xilef#26]
what if we add like alias, for every user?
the idea is like
&alias h "driller dig"
so doing
&h 5
would do "&driller dig 5"
or maybe
&alias e = "dig 100"
so doing
&driller e
would do "&driller dig 100"

this is just an idea and im not entirely sure about it, I might easily scrap it unless its a good idea

**Comment by Felix-44** [comment]
idea for the aliases, we dont limit them (so they can replace commands _and_ arguments), but if someone screws themselves, the bot will have a button to remove all aliases when pinging it
@LJMSU does this sound good?

**Comment by LJMSU** [comment]
That's good but if you have a hard time using buttons you could do something like `@Xilef clear-aliases`.

**Comment by Felix-44** [comment]
Ill start working on this command soon
