### ISSUE TITLE
Migrate to node v16

### ISSUE THREAD

**Issue by LJMSU** [Felix-44/Xilef#33]
Migrate to node version 16, which would become LTS soon in October. This would allow upgrading to discord.js@13, allowing to fix these issues:

- #19

**Comment by Felix-44** [comment]
would upgrading discord.js to v13 break the buttons? since discord.js v13 should have their own way know apprently

**Comment by LJMSU** [comment]
Maybe, but I'm waiting for October first to test the new API.

**Comment by Felix-44** [comment]
perhaps someone should first host the bot with the new versions of nodejs and discord.js to see if everything work, and then I can upgrade it

**Comment by LJMSU** [comment]
Maybe I can use nvm.
