### ISSUE TITLE
&stocks's data lost

### ISSUE THREAD

**Issue by Felix-44** [Felix-44/Xilef#57]
in the mania of fixing stuff somehow we lost the file xilefunds.json and now the command is pretty much useless
@Volas171 if you have any backup of the file let us know

**Comment by Volas171** [comment]
well, no, data loss is data lost (all backups got erased because of some reason)

**Comment by Fabizocker456** [comment]
Idea: implement a ledger in which all events regarding money are logged, so you can restore financial data up to a certain degree, even if the most recent version gets deleted

**Comment by Volas171** [comment]
that wouldnt prevent loss, it would be another pain involving 2000 more .jsons

**Comment by Volas171** [comment]
probably wouldnt be such a pain if we migrated to MySQL instead of .json files

**Comment by Felix-44** [comment]
> Idea: implement a ledger in which all events regarding money are logged, so you can restore financial data up to a certain degree, even if the most recent version gets deleted. That would also prevent any future data loss.

that _was_ what xilefunds.json did

**Comment by Felix-44** [comment]
randomly found a .json from old commits, for now we can use that one to at least have the command working
